/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConvertionRecord } from './ConvertionRecord';
import {
    ConvertionRecordFromJSON,
    ConvertionRecordFromJSONTyped,
    ConvertionRecordToJSON,
} from './ConvertionRecord';

/**
 * Данные для добавления в задачу на конвертацию адресов
 * @export
 * @interface AddConversionDataInput
 */
export interface AddConversionDataInput {
    /**
     * Идентификатор задачи на конвертацию адресов
     * @type {string}
     * @memberof AddConversionDataInput
     */
    taskGuid?: string;
    /**
     * Блок данных
     * @type {Array<ConvertionRecord>}
     * @memberof AddConversionDataInput
     */
    data?: Array<ConvertionRecord> | null;
}

/**
 * Check if a given object implements the AddConversionDataInput interface.
 */
export function instanceOfAddConversionDataInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddConversionDataInputFromJSON(json: any): AddConversionDataInput {
    return AddConversionDataInputFromJSONTyped(json, false);
}

export function AddConversionDataInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddConversionDataInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskGuid': !exists(json, 'task_guid') ? undefined : json['task_guid'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ConvertionRecordFromJSON)),
    };
}

export function AddConversionDataInputToJSON(value?: AddConversionDataInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_guid': value.taskGuid,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ConvertionRecordToJSON)),
    };
}

