/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Результат возвращающий идентификатор уведомления
 * @export
 * @interface AddNoticeResult
 */
export interface AddNoticeResult {
    /**
     * Идентификатор уведомления
     * @type {number}
     * @memberof AddNoticeResult
     */
    noticeId?: number;
}

/**
 * Check if a given object implements the AddNoticeResult interface.
 */
export function instanceOfAddNoticeResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddNoticeResultFromJSON(json: any): AddNoticeResult {
    return AddNoticeResultFromJSONTyped(json, false);
}

export function AddNoticeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddNoticeResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'noticeId': !exists(json, 'notice_id') ? undefined : json['notice_id'],
    };
}

export function AddNoticeResultToJSON(value?: AddNoticeResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notice_id': value.noticeId,
    };
}

