/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressHintItem
 */
export interface AddressHintItem {
    /**
     * 
     * @type {number}
     * @memberof AddressHintItem
     */
    objectId?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressHintItem
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressHintItem
     */
    fullNameHtml?: string | null;
}

/**
 * Check if a given object implements the AddressHintItem interface.
 */
export function instanceOfAddressHintItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressHintItemFromJSON(json: any): AddressHintItem {
    return AddressHintItemFromJSONTyped(json, false);
}

export function AddressHintItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressHintItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': !exists(json, 'object_id') ? undefined : json['object_id'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'fullNameHtml': !exists(json, 'full_name_html') ? undefined : json['full_name_html'],
    };
}

export function AddressHintItemToJSON(value?: AddressHintItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object_id': value.objectId,
        'full_name': value.fullName,
        'full_name_html': value.fullNameHtml,
    };
}

