/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDetails } from './AddressDetails';
import {
    AddressDetailsFromJSON,
    AddressDetailsFromJSONTyped,
    AddressDetailsToJSON,
} from './AddressDetails';

/**
 * Расширенная информация, полученная через сервис
 * @export
 * @interface AddressDetailsResult
 */
export interface AddressDetailsResult {
    /**
     * 
     * @type {AddressDetails}
     * @memberof AddressDetailsResult
     */
    addressDetails?: AddressDetails;
}

/**
 * Check if a given object implements the AddressDetailsResult interface.
 */
export function instanceOfAddressDetailsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDetailsResultFromJSON(json: any): AddressDetailsResult {
    return AddressDetailsResultFromJSONTyped(json, false);
}

export function AddressDetailsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDetailsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressDetails': !exists(json, 'address_details') ? undefined : AddressDetailsFromJSON(json['address_details']),
    };
}

export function AddressDetailsResultToJSON(value?: AddressDetailsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_details': AddressDetailsToJSON(value.addressDetails),
    };
}

