/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressItem } from './AddressItem';
import {
    AddressItemFromJSON,
    AddressItemFromJSONTyped,
    AddressItemToJSON,
} from './AddressItem';

/**
 * Адресные элементы, полученные через сервис
 * @export
 * @interface AddressesResult
 */
export interface AddressesResult {
    /**
     * Список адресных элементов
     * @type {Array<AddressItem>}
     * @memberof AddressesResult
     */
    addresses?: Array<AddressItem> | null;
}

/**
 * Check if a given object implements the AddressesResult interface.
 */
export function instanceOfAddressesResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressesResultFromJSON(json: any): AddressesResult {
    return AddressesResultFromJSONTyped(json, false);
}

export function AddressesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressesResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': !exists(json, 'addresses') ? undefined : (json['addresses'] === null ? null : (json['addresses'] as Array<any>).map(AddressItemFromJSON)),
    };
}

export function AddressesResultToJSON(value?: AddressesResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': value.addresses === undefined ? undefined : (value.addresses === null ? null : (value.addresses as Array<any>).map(AddressItemToJSON)),
    };
}

