/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDetails } from './AddressDetails';
import {
    AddressDetailsFromJSON,
    AddressDetailsFromJSONTyped,
    AddressDetailsToJSON,
} from './AddressDetails';
import type { AddressLevel } from './AddressLevel';
import {
    AddressLevelFromJSON,
    AddressLevelFromJSONTyped,
    AddressLevelToJSON,
} from './AddressLevel';
import type { AddressPart } from './AddressPart';
import {
    AddressPartFromJSON,
    AddressPartFromJSONTyped,
    AddressPartToJSON,
} from './AddressPart';
import type { AddressType } from './AddressType';
import {
    AddressTypeFromJSON,
    AddressTypeFromJSONTyped,
    AddressTypeToJSON,
} from './AddressType';
import type { ObjectRef } from './ObjectRef';
import {
    ObjectRefFromJSON,
    ObjectRefFromJSONTyped,
    ObjectRefToJSON,
} from './ObjectRef';

/**
 * 
 * @export
 * @interface AddressItem
 */
export interface AddressItem {
    /**
     * 
     * @type {number}
     * @memberof AddressItem
     */
    objectId?: number;
    /**
     * 
     * @type {AddressLevel}
     * @memberof AddressItem
     */
    objectLevelId?: AddressLevel;
    /**
     * 
     * @type {number}
     * @memberof AddressItem
     */
    operationTypeId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AddressItem
     */
    objectGuid?: string;
    /**
     * 
     * @type {AddressType}
     * @memberof AddressItem
     */
    addressType?: AddressType;
    /**
     * 
     * @type {string}
     * @memberof AddressItem
     */
    fullName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressItem
     */
    regionCode?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AddressItem
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddressItem
     */
    path?: string | null;
    /**
     * 
     * @type {AddressDetails}
     * @memberof AddressItem
     */
    addressDetails?: AddressDetails;
    /**
     * 
     * @type {ObjectRef}
     * @memberof AddressItem
     */
    successorRef?: ObjectRef;
    /**
     * 
     * @type {Array<AddressPart>}
     * @memberof AddressItem
     */
    hierarchy?: Array<AddressPart> | null;
}

/**
 * Check if a given object implements the AddressItem interface.
 */
export function instanceOfAddressItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressItemFromJSON(json: any): AddressItem {
    return AddressItemFromJSONTyped(json, false);
}

export function AddressItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': !exists(json, 'object_id') ? undefined : json['object_id'],
        'objectLevelId': !exists(json, 'object_level_id') ? undefined : AddressLevelFromJSON(json['object_level_id']),
        'operationTypeId': !exists(json, 'operation_type_id') ? undefined : json['operation_type_id'],
        'objectGuid': !exists(json, 'object_guid') ? undefined : json['object_guid'],
        'addressType': !exists(json, 'address_type') ? undefined : AddressTypeFromJSON(json['address_type']),
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'regionCode': !exists(json, 'region_code') ? undefined : json['region_code'],
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'addressDetails': !exists(json, 'address_details') ? undefined : AddressDetailsFromJSON(json['address_details']),
        'successorRef': !exists(json, 'successor_ref') ? undefined : ObjectRefFromJSON(json['successor_ref']),
        'hierarchy': !exists(json, 'hierarchy') ? undefined : (json['hierarchy'] === null ? null : (json['hierarchy'] as Array<any>).map(AddressPartFromJSON)),
    };
}

export function AddressItemToJSON(value?: AddressItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object_id': value.objectId,
        'object_level_id': AddressLevelToJSON(value.objectLevelId),
        'operation_type_id': value.operationTypeId,
        'object_guid': value.objectGuid,
        'address_type': AddressTypeToJSON(value.addressType),
        'full_name': value.fullName,
        'region_code': value.regionCode,
        'is_active': value.isActive,
        'path': value.path,
        'address_details': AddressDetailsToJSON(value.addressDetails),
        'successor_ref': ObjectRefToJSON(value.successorRef),
        'hierarchy': value.hierarchy === undefined ? undefined : (value.hierarchy === null ? null : (value.hierarchy as Array<any>).map(AddressPartToJSON)),
    };
}

