/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AddressLevel = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_14: 14,
    NUMBER_17: 17
} as const;
export type AddressLevel = typeof AddressLevel[keyof typeof AddressLevel];


export function AddressLevelFromJSON(json: any): AddressLevel {
    return AddressLevelFromJSONTyped(json, false);
}

export function AddressLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressLevel {
    return json as AddressLevel;
}

export function AddressLevelToJSON(value?: AddressLevel | null): any {
    return value as any;
}

