/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressDetails
 */
export interface AddressDetails {
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    ifnsUl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    ifnsFl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    ifnsTul?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    ifnsTfl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    okato?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    oktmo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    kladrCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    cadastralNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    apartBuilding?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    removeCadastr?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDetails
     */
    oktmoBudget?: string | null;
}

/**
 * Check if a given object implements the AddressDetails interface.
 */
export function instanceOfAddressDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDetailsFromJSON(json: any): AddressDetails {
    return AddressDetailsFromJSONTyped(json, false);
}

export function AddressDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postalCode': !exists(json, 'postal_code') ? undefined : json['postal_code'],
        'ifnsUl': !exists(json, 'ifns_ul') ? undefined : json['ifns_ul'],
        'ifnsFl': !exists(json, 'ifns_fl') ? undefined : json['ifns_fl'],
        'ifnsTul': !exists(json, 'ifns_tul') ? undefined : json['ifns_tul'],
        'ifnsTfl': !exists(json, 'ifns_tfl') ? undefined : json['ifns_tfl'],
        'okato': !exists(json, 'okato') ? undefined : json['okato'],
        'oktmo': !exists(json, 'oktmo') ? undefined : json['oktmo'],
        'kladrCode': !exists(json, 'kladr_code') ? undefined : json['kladr_code'],
        'cadastralNumber': !exists(json, 'cadastral_number') ? undefined : json['cadastral_number'],
        'apartBuilding': !exists(json, 'apart_building') ? undefined : json['apart_building'],
        'removeCadastr': !exists(json, 'remove_cadastr') ? undefined : json['remove_cadastr'],
        'oktmoBudget': !exists(json, 'oktmo_budget') ? undefined : json['oktmo_budget'],
    };
}

export function AddressDetailsToJSON(value?: AddressDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postal_code': value.postalCode,
        'ifns_ul': value.ifnsUl,
        'ifns_fl': value.ifnsFl,
        'ifns_tul': value.ifnsTul,
        'ifns_tfl': value.ifnsTfl,
        'okato': value.okato,
        'oktmo': value.oktmo,
        'kladr_code': value.kladrCode,
        'cadastral_number': value.cadastralNumber,
        'apart_building': value.apartBuilding,
        'remove_cadastr': value.removeCadastr,
        'oktmo_budget': value.oktmoBudget,
    };
}

