/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressObject
 */
export interface AddressObject {
    /**
     * 
     * @type {string}
     * @memberof AddressObject
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressObject
     */
    typeName?: string | null;
}

/**
 * Check if a given object implements the AddressObject interface.
 */
export function instanceOfAddressObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressObjectFromJSON(json: any): AddressObject {
    return AddressObjectFromJSONTyped(json, false);
}

export function AddressObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'typeName': !exists(json, 'type_name') ? undefined : json['type_name'],
    };
}

export function AddressObjectToJSON(value?: AddressObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type_name': value.typeName,
    };
}

