/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Результат проверки
 * @export
 * @interface CheckResult
 */
export interface CheckResult {
    /**
     * Результат
     * @type {boolean}
     * @memberof CheckResult
     */
    check?: boolean;
}

/**
 * Check if a given object implements the CheckResult interface.
 */
export function instanceOfCheckResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckResultFromJSON(json: any): CheckResult {
    return CheckResultFromJSONTyped(json, false);
}

export function CheckResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'check': !exists(json, 'check') ? undefined : json['check'],
    };
}

export function CheckResultToJSON(value?: CheckResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'check': value.check,
    };
}

