/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversionTaskStatusAndStatistics
 */
export interface ConversionTaskStatusAndStatistics {
    /**
     * 
     * @type {string}
     * @memberof ConversionTaskStatusAndStatistics
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ConversionTaskStatusAndStatistics
     */
    totalRecords?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversionTaskStatusAndStatistics
     */
    processed?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversionTaskStatusAndStatistics
     */
    converted?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversionTaskStatusAndStatistics
     */
    nonconverted?: number;
    /**
     * 
     * @type {number}
     * @memberof ConversionTaskStatusAndStatistics
     */
    blockCount?: number;
}

/**
 * Check if a given object implements the ConversionTaskStatusAndStatistics interface.
 */
export function instanceOfConversionTaskStatusAndStatistics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversionTaskStatusAndStatisticsFromJSON(json: any): ConversionTaskStatusAndStatistics {
    return ConversionTaskStatusAndStatisticsFromJSONTyped(json, false);
}

export function ConversionTaskStatusAndStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversionTaskStatusAndStatistics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'totalRecords': !exists(json, 'total_records') ? undefined : json['total_records'],
        'processed': !exists(json, 'processed') ? undefined : json['processed'],
        'converted': !exists(json, 'converted') ? undefined : json['converted'],
        'nonconverted': !exists(json, 'nonconverted') ? undefined : json['nonconverted'],
        'blockCount': !exists(json, 'block_count') ? undefined : json['block_count'],
    };
}

export function ConversionTaskStatusAndStatisticsToJSON(value?: ConversionTaskStatusAndStatistics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'total_records': value.totalRecords,
        'processed': value.processed,
        'converted': value.converted,
        'nonconverted': value.nonconverted,
        'block_count': value.blockCount,
    };
}

