/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Результат создания задачи на конвертацию адресов
 * @export
 * @interface CreateConversionTaskResult
 */
export interface CreateConversionTaskResult {
    /**
     * Идентификатор задачи
     * @type {string}
     * @memberof CreateConversionTaskResult
     */
    taskGuid?: string;
}

/**
 * Check if a given object implements the CreateConversionTaskResult interface.
 */
export function instanceOfCreateConversionTaskResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateConversionTaskResultFromJSON(json: any): CreateConversionTaskResult {
    return CreateConversionTaskResultFromJSONTyped(json, false);
}

export function CreateConversionTaskResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConversionTaskResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskGuid': !exists(json, 'task_guid') ? undefined : json['task_guid'],
    };
}

export function CreateConversionTaskResultToJSON(value?: CreateConversionTaskResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_guid': value.taskGuid,
    };
}

