/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Метод выполнен с ошибкой
 * @export
 * @interface ErrorResult
 */
export interface ErrorResult {
    /**
     * Описание ошибки
     * @type {string}
     * @memberof ErrorResult
     */
    description?: string | null;
    /**
     * Идентификатор запроса
     * @type {string}
     * @memberof ErrorResult
     */
    readonly activityId?: string | null;
    /**
     * Признак успешного выполнения
     * @type {boolean}
     * @memberof ErrorResult
     */
    readonly success?: boolean;
}

/**
 * Check if a given object implements the ErrorResult interface.
 */
export function instanceOfErrorResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorResultFromJSON(json: any): ErrorResult {
    return ErrorResultFromJSONTyped(json, false);
}

export function ErrorResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'activityId': !exists(json, 'activity_id') ? undefined : json['activity_id'],
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function ErrorResultToJSON(value?: ErrorResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}

