/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EstateObject
 */
export interface EstateObject {
    /**
     * 
     * @type {string}
     * @memberof EstateObject
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EstateObject
     */
    typeName?: string | null;
}

/**
 * Check if a given object implements the EstateObject interface.
 */
export function instanceOfEstateObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EstateObjectFromJSON(json: any): EstateObject {
    return EstateObjectFromJSONTyped(json, false);
}

export function EstateObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): EstateObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'typeName': !exists(json, 'type_name') ? undefined : json['type_name'],
    };
}

export function EstateObjectToJSON(value?: EstateObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'type_name': value.typeName,
    };
}

