/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FiasType } from './FiasType';
import {
    FiasTypeFromJSON,
    FiasTypeFromJSONTyped,
    FiasTypeToJSON,
} from './FiasType';

/**
 * Типы ФИАС
 * @export
 * @interface FiasTypesResult
 */
export interface FiasTypesResult {
    /**
     * Список типов ФИАС
     * @type {Array<FiasType>}
     * @memberof FiasTypesResult
     */
    types?: Array<FiasType> | null;
}

/**
 * Check if a given object implements the FiasTypesResult interface.
 */
export function instanceOfFiasTypesResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FiasTypesResultFromJSON(json: any): FiasTypesResult {
    return FiasTypesResultFromJSONTyped(json, false);
}

export function FiasTypesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiasTypesResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'types': !exists(json, 'types') ? undefined : (json['types'] === null ? null : (json['types'] as Array<any>).map(FiasTypeFromJSON)),
    };
}

export function FiasTypesResultToJSON(value?: FiasTypesResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'types': value.types === undefined ? undefined : (value.types === null ? null : (value.types as Array<any>).map(FiasTypeToJSON)),
    };
}

