/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressHintItem } from './AddressHintItem';
import {
    AddressHintItemFromJSON,
    AddressHintItemFromJSONTyped,
    AddressHintItemToJSON,
} from './AddressHintItem';

/**
 * Подсказки для поиска, полученые от сервиса
 * @export
 * @interface HintResult
 */
export interface HintResult {
    /**
     * Список подсказок для поиска
     * @type {Array<AddressHintItem>}
     * @memberof HintResult
     */
    hints?: Array<AddressHintItem> | null;
}

/**
 * Check if a given object implements the HintResult interface.
 */
export function instanceOfHintResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HintResultFromJSON(json: any): HintResult {
    return HintResultFromJSONTyped(json, false);
}

export function HintResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): HintResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hints': !exists(json, 'hints') ? undefined : (json['hints'] === null ? null : (json['hints'] as Array<any>).map(AddressHintItemFromJSON)),
    };
}

export function HintResultToJSON(value?: HintResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hints': value.hints === undefined ? undefined : (value.hints === null ? null : (value.hints as Array<any>).map(AddressHintItemToJSON)),
    };
}

