/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IFetchChangesTaskResultBlock
 */
export interface IFetchChangesTaskResultBlock {
    /**
     * 
     * @type {Array<string>}
     * @memberof IFetchChangesTaskResultBlock
     */
    readonly block?: Array<string> | null;
}

/**
 * Check if a given object implements the IFetchChangesTaskResultBlock interface.
 */
export function instanceOfIFetchChangesTaskResultBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IFetchChangesTaskResultBlockFromJSON(json: any): IFetchChangesTaskResultBlock {
    return IFetchChangesTaskResultBlockFromJSONTyped(json, false);
}

export function IFetchChangesTaskResultBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): IFetchChangesTaskResultBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'block': !exists(json, 'block') ? undefined : json['block'],
    };
}

export function IFetchChangesTaskResultBlockToJSON(value?: IFetchChangesTaskResultBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

