/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoticeFilterObject
 */
export interface NoticeFilterObject {
    /**
     * 
     * @type {string}
     * @memberof NoticeFilterObject
     */
    senderCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NoticeFilterObject
     */
    requestId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NoticeFilterObject
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof NoticeFilterObject
     */
    endDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof NoticeFilterObject
     */
    status?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NoticeFilterObject
     */
    parentObjectGuid?: string | null;
}

/**
 * Check if a given object implements the NoticeFilterObject interface.
 */
export function instanceOfNoticeFilterObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoticeFilterObjectFromJSON(json: any): NoticeFilterObject {
    return NoticeFilterObjectFromJSONTyped(json, false);
}

export function NoticeFilterObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeFilterObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'senderCode': !exists(json, 'sender_code') ? undefined : json['sender_code'],
        'requestId': !exists(json, 'request_id') ? undefined : json['request_id'],
        'startDate': !exists(json, 'start_date') ? undefined : (json['start_date'] === null ? null : new Date(json['start_date'])),
        'endDate': !exists(json, 'end_date') ? undefined : (json['end_date'] === null ? null : new Date(json['end_date'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'parentObjectGuid': !exists(json, 'parent_object_guid') ? undefined : json['parent_object_guid'],
    };
}

export function NoticeFilterObjectToJSON(value?: NoticeFilterObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sender_code': value.senderCode,
        'request_id': value.requestId,
        'start_date': value.startDate === undefined ? undefined : (value.startDate === null ? null : value.startDate.toISOString()),
        'end_date': value.endDate === undefined ? undefined : (value.endDate === null ? null : value.endDate.toISOString()),
        'status': value.status,
        'parent_object_guid': value.parentObjectGuid,
    };
}

