/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoticeType = {
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type NoticeType = typeof NoticeType[keyof typeof NoticeType];


export function NoticeTypeFromJSON(json: any): NoticeType {
    return NoticeTypeFromJSONTyped(json, false);
}

export function NoticeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeType {
    return json as NoticeType;
}

export function NoticeTypeToJSON(value?: NoticeType | null): any {
    return value as any;
}

