/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NoticeSourceType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type NoticeSourceType = typeof NoticeSourceType[keyof typeof NoticeSourceType];


export function NoticeSourceTypeFromJSON(json: any): NoticeSourceType {
    return NoticeSourceTypeFromJSONTyped(json, false);
}

export function NoticeSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeSourceType {
    return json as NoticeSourceType;
}

export function NoticeSourceTypeToJSON(value?: NoticeSourceType | null): any {
    return value as any;
}

