/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NoticeItem } from './NoticeItem';
import {
    NoticeItemFromJSON,
    NoticeItemFromJSONTyped,
    NoticeItemToJSON,
} from './NoticeItem';

/**
 * Результат возвращающий идентификатор уведомления
 * @export
 * @interface NoticeItemsResult
 */
export interface NoticeItemsResult {
    /**
     * Список уведомлений
     * @type {Array<NoticeItem>}
     * @memberof NoticeItemsResult
     */
    notices?: Array<NoticeItem> | null;
}

/**
 * Check if a given object implements the NoticeItemsResult interface.
 */
export function instanceOfNoticeItemsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoticeItemsResultFromJSON(json: any): NoticeItemsResult {
    return NoticeItemsResultFromJSONTyped(json, false);
}

export function NoticeItemsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoticeItemsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notices': !exists(json, 'notices') ? undefined : (json['notices'] === null ? null : (json['notices'] as Array<any>).map(NoticeItemFromJSON)),
    };
}

export function NoticeItemsResultToJSON(value?: NoticeItemsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notices': value.notices === undefined ? undefined : (value.notices === null ? null : (value.notices as Array<any>).map(NoticeItemToJSON)),
    };
}

