/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectRef
 */
export interface ObjectRef {
    /**
     * 
     * @type {number}
     * @memberof ObjectRef
     */
    objectId?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectRef
     */
    objectGuid?: string;
}

/**
 * Check if a given object implements the ObjectRef interface.
 */
export function instanceOfObjectRef(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectRefFromJSON(json: any): ObjectRef {
    return ObjectRefFromJSONTyped(json, false);
}

export function ObjectRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': !exists(json, 'object_id') ? undefined : json['object_id'],
        'objectGuid': !exists(json, 'object_guid') ? undefined : json['object_guid'],
    };
}

export function ObjectRefToJSON(value?: ObjectRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'object_id': value.objectId,
        'object_guid': value.objectGuid,
    };
}

