/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressItem } from './AddressItem';
import {
    AddressItemFromJSON,
    AddressItemFromJSONTyped,
    AddressItemToJSON,
} from './AddressItem';

/**
 * 
 * @export
 * @interface SearchByPartsResult
 */
export interface SearchByPartsResult {
    /**
     * 
     * @type {string}
     * @memberof SearchByPartsResult
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SearchByPartsResult
     */
    description?: string | null;
    /**
     * 
     * @type {AddressItem}
     * @memberof SearchByPartsResult
     */
    addressItem?: AddressItem;
    /**
     * 
     * @type {AddressItem}
     * @memberof SearchByPartsResult
     */
    lastFoundItem?: AddressItem;
}

/**
 * Check if a given object implements the SearchByPartsResult interface.
 */
export function instanceOfSearchByPartsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchByPartsResultFromJSON(json: any): SearchByPartsResult {
    return SearchByPartsResultFromJSONTyped(json, false);
}

export function SearchByPartsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchByPartsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'addressItem': !exists(json, 'address_item') ? undefined : AddressItemFromJSON(json['address_item']),
        'lastFoundItem': !exists(json, 'last_found_item') ? undefined : AddressItemFromJSON(json['last_found_item']),
    };
}

export function SearchByPartsResultToJSON(value?: SearchByPartsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
        'description': value.description,
        'address_item': AddressItemToJSON(value.addressItem),
        'last_found_item': AddressItemToJSON(value.lastFoundItem),
    };
}

