/* tslint:disable */
/* eslint-disable */
/**
 * SPAS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Метод успешно выполнен
 * @export
 * @interface SuccessResult
 */
export interface SuccessResult {
    /**
     * Признак успешного выполнения
     * @type {boolean}
     * @memberof SuccessResult
     */
    readonly success?: boolean;
}

/**
 * Check if a given object implements the SuccessResult interface.
 */
export function instanceOfSuccessResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SuccessResultFromJSON(json: any): SuccessResult {
    return SuccessResultFromJSONTyped(json, false);
}

export function SuccessResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function SuccessResultToJSON(value?: SuccessResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

